version: '2'
volumes:
    mosquitto:
    zigbee2mqtt:
services:
  mqtt:
    build: mqtt
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - mosquitto:/mosquitto/data
  zigbee2mqtt:
    build: zigbee2mqtt
    restart: always
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0
    environment:
      - DATA=/app/data
      - TZ=Europe/Berlin
